<main id="home">
    <div id="argent">
        <a id="logout" href="./index.php">Déconnexion</a>
        <div><h2><?= $data['total']?> €</h2></div>
        <div>
            <a href="./index.php?route=ajouter">Ajouter</a>
            <a href="./index.php?route=depenser">Dépenser</a>
            <a href="./index.php?route=rembourser">Rembourser</a>
        </div>
    </div>
    <div>
        <!-- <ul>
            <?php // foreach(){ ?>
                <div></div>
            <?php //} ?>
        </ul> -->
    </div>
</main>